### PR TITLE
Andrew units work

### PR DESCRIPTION
**Pull request by mtbc**
Definitely needs careful review and some patching, is a hasty where-I'm-up-to.

### CODE REVIEW

**Comment by joshmoore** [comment]
Who's currently working on this? Is this `WIP` commit to be rewritten?

**Comment by mtbc** [comment]
@qidane's now taking a look; it was easier for him as a PR. Rewriting commit seems reasonable. (I am just now looking over the changes to see if I spot any mistakes.) I think he's taking over finishing this off, but I am certainly happy to go over and join him in figuring out anything outstanding.

**Comment by qidane** [comment]
Merged on the command lie along with a bug fix.

**Comment by qidane** [comment]
Resolved elsewhere and force-pushed to the units-length branch

**Pull request closed without merging**
